server:
  port: 9300
  
spring:  application:    name: CONFIG-SERVER
  cloud:    config:      server:        git:          uri: https://github.com/Ambarishsi/SpringbootMS-Config-Server
          clone-on-start: true

